name: Deploy to CF
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List contents of current directory
        run: ls -la

      - name: Install CF CLI
        run: |
          wget -q -O cf.tar.gz "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=7.4.0&source=github-rel"
          sudo tar xzf cf.tar.gz --wildcards --directory /usr/local/bin/ "cf*"
          /usr/local/bin/cf --version

    
