name: Deploy to CF
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install CF CLI
        run: |
          curl -sLo cf.tgz https://packages.cloudfoundry.org/stable?release=linux64-binary&version=latest
          tar -zxf cf.tgz
          sudo mv cf /usr/local/bin/

      - name: Verify CF CLI installation
        run: cf --version
