name: Deploy to CF
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List contents of current directory
        run: ls -la

      - name: Install CF CLI
        run: |
          # Download the CF CLI binary using curl
          wget -q -O cf.tar.gz "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=7.4.0&source=github-rel"
           # Print the contents of the current directory for debugging
          ls -la
          $pwd
          # Extract the CF CLI binary
          tar -zxvf cf.tar.gz

          # Move the CF CLI binary to a directory in your PATH
          sudo mv cf /usr/local/bin/

      - name: Verify CF CLI installation
        run: cf --version

      # Add more steps for your deployment process here
